# Generated by Django 4.2.1 on 2023-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField()),
                ('mean', models.IntegerField()),
                ('median', models.IntegerField()),
                ('mode', models.IntegerField()),
            ],
        ),
    ]
